# Generated by Django 4.2.4 on 2023-09-11 10:15

import admin_section.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=admin_section.models.get_image_upload_path),
        ),
    ]
